version: "3"

services:
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
    volumes:
      - ./pkg/db/data:/data

  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    volumes:
      - ./pkg/db/seeds:/seeds
    command: /bin/sh -c "/scripts/init.sh"
    links:
      - mongo

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dev
    ports:
      - "1323:1323"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    links:
      - mongo
    volumes:
      - ./:/go/src/app
      - ./vendor/:/go/src/app/vendor
