apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  labels:
    app: golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
        - name: podchef
          image: podchef/production
          ports:
            - containerPort: 1323
---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
spec:
  selector:
    app: golang
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323
---
# kind: Service
# apiVersion: v1
# metadata:
#   name: mongodb
# spec:
#   type: ClusterIP
#   ports:
#     - port: 27017
#       targetPort: 27017
# ---
# kind: Endpoints
# apiVersion: v1
# metadata:
#   name: mongodb
# subsets:
#   - addresses:
#       - ip: 127.0.0.1
#     ports:
#       - port: 27017

# kind: Service
# apiVersion: v1
# metadata:
#   name: mongodb
# spec:
#   type: ExternalName
#   # https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds
#   externalName: host.docker.internal
#   ports:
#     - port: 27017
#       name: mongodb
kind: Service
apiVersion: v1
metadata:
  name: mongodb
spec:
  type: ExternalName
  externalName: host.docker.internal
